server.modules += ( "mod_proxy" )

server.document-root = "/var/www/gardenfront"

$HTTP["url"] =~ "^/api/" {
    proxy.server = ( "" => (
        ( "host" => "127.0.0.1", "port" => 8000 )
    ))
    proxy.header = (
        "map-urlpath" => ( "/api/" => "/" ),
        "upgrade" => "enable"
    )
}

$HTTP["url"] =~ "^/(docs|redoc|openapi.json)" {
    proxy.server = ( "" => (
        ( "host" => "127.0.0.1", "port" => 8000 )
    ))
}
